#!/bin/bash  
### environment variables
# FAKE_ROOT: specifies a fake root. if empty, installs to root
# BIN_DIR: system executables
# LIB_DIR: system libraries
# CONFIG_DIR: system configuration dir
# DOC_DIR: documentation dir
pushd $(dirname $0)

PROJECT_NAME=sodalite

# providing fallbacks
[ -z $BIN_DIR ] && BIN_DIR=/usr/bin
[ -z $DOC_DIR ] && DOC_DIR=/usr/share/doc
[ -z $DATA_DIR ] && DATA_DIR=/usr/share
[ -z $CONFIG_DIR ] && CONFIG_DIR=/etc
[ -z $LIB_DIR ] && LIB_DIR=/usr/lib

# add project suffix
CONFIG_FILE=${CONFIG_DIR}/${PROJECT_NAME}.conf
LIB_DIR=${LIB_DIR}/${PROJECT_NAME}
DATA_DIR=${DATA_DIR}/${PROJECT_NAME}
DOC_DIR=${DOC_DIR}/${PROJECT_NAME}

# add prefix fakeroot
FAKE_CONFIG_DIR=${FAKE_ROOT}${CONFIG_DIR}
FAKE_CONFIG_FILE=${FAKE_ROOT}/${CONFIG_FILE}
FAKE_BIN_DIR=${FAKE_ROOT}${BIN_DIR}
FAKE_LIB_DIR=${FAKE_ROOT}${LIB_DIR}
FAKE_DATA_DIR=${FAKE_ROOT}${DATA_DIR}
FAKE_DOC_DIR=${FAKE_ROOT}${DOC_DIR}
FAKE_LOG_FILE=${FAKE_ROOT}/var/log/sodalite.log

install -d $FAKE_LIB_DIR
install -D src/* $FAKE_LIB_DIR

install -d $FAKE_DATA_DIR
install -D util/shell-integration.sh $FAKE_DATA_DIR/shell-integration.sh

mkdir -p $(dirname $FAKE_LOG_FILE)
touch $FAKE_LOG_FILE && chmod 666 $FAKE_LOG_FILE

mkdir -p $FAKE_BIN_DIR
awk 'NR==1 {print; print "LIB_DIR='"$LIB_DIR"'"; print "CONFIG_FILE='"$CONFIG_FILE"'"} NR!=1'  $PROJECT_NAME > "$FAKE_BIN_DIR/$PROJECT_NAME"
chmod 755 $FAKE_BIN_DIR/$PROJECT_NAME

install -D --backup -m644 "docs/example.conf" $FAKE_CONFIG_FILE
