#!/bin/bash  
### environment variables
# FAKE_ROOT: specifies a fake root. if empty, installs to root
# BIN_DIR: system executables
# LIB_DIR: system libraries
# CONFIG_DIR: system configuration dir
# DOC_DIR: documentation dir
pushd $(dirname $0)

PROJECT_NAME=sodalite

# providing fallbacks
[ -z $BIN_DIR ] && BIN_DIR=/usr/bin
[ -z $DOC_DIR ] && DOC_DIR=/usr/share/doc
[ -z $CONFIG_DIR ] && CONFIG_DIR=/etc
[ -z $LIB_DIR ] && LIB_DIR=/usr/lib

CONFIG_DIR=${FAKE_ROOT}${CONFIG_DIR}
CONFIG_FILE=$CONFIG_DIR/${PROJECT_NAME}.conf
BIN_DIR=${FAKE_ROOT}${BIN_DIR}
LIB_DIR=${FAKE_ROOT}${LIB_DIR}/${PROJECT_NAME}
DOC_DIR=${FAKE_ROOT}${DOC_DIR}/${PROJECT_NAME}

install -d $LIB_DIR
install -D src/* $LIB_DIR

mkdir -p $BIN_DIR
awk 'NR==1 {print; print "LIB_DIR='"$LIB_DIR"'"; print "CONFIG_FILE='"$CONFIG_FILE"'"} NR!=1'  $PROJECT_NAME > "$BIN_DIR/$PROJECT_NAME"
chmod 755 $BIN_DIR/$PROJECT_NAME

install -D --backup -m644 "docs/example.conf" $CONFIG_FILE

[ -L "$BIN_DIR/sl" ] || ln -s "${FAKE_ROOT}/usr/bin/sodalite" ${FAKE_ROOT}/usr/bin/sl

popd
