[tool.semantic_release]
version_variable = [
    "sodalite/util/version.py:VERSION",
]
branch = "master"
upload_to_pypi = false
upload_to_release = false
build_command = "pip install poetry && poetry build"
commit_message = "chore(release): update to {version}"
