#!/bin/bash
# development script for sodalite
set -eu

{
    project_root="$(dirname "$(readlink -f "$0")")/.."
    export CONFIG_FILE="$project_root/sodalite/core/sodalite.conf"
    export PYTHONPATH="$project_root:${PYTHONPATH:-}"
    export DB_PATH="$project_root/db.sqlite"
    make -C "$project_root" deps
    source "$project_root/venv/bin/activate"
} > /dev/null
python -m sodalite "$@"

