#!/bin/bash  


## set up environment
APPNAME=sodalite
SOURCES=/usr/share/$APPNAME
export SODALITE_LOG=/var/log/sodalite/sodalite.log
XDG_CONFIG=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_DATA=${XDG_DATA_HOME:-$HOME/.local/share}
SODALITE_CONFIG_DIR=${XDG_CONFIG}/$APPNAME
SODALITE_DATA_DIR=${XDG_DATA}/$APPNAME
export SODALITE_BOOKMARK_DIR=${SODALITE_CONFIG_DIR}/bookmarks
mkdir -p $SODALITE_GLOBAL_CONFIG_DIR $SODALITE_DATA_DIR $SODALITE_BOOKMARK_DIR &2> /dev/null
export SODALITE_DB_PATH=${SODALITE_DATA_DIR}/db.sqlite
[ -f $SODALITE_DB_PATH ] || \
    echo "CREATE TABLE IF NOT EXISTS files (
    name text NOT NULL,
    parent text NOT NULL,
    key text NOT NULL,
    frequency INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY ( name, parent )
);" | sqlite3 $SODALITE_DB_PATH

# $1: starting directory
export SODALITE_STARTING_DIR=${1:-$HOME}

# handle config
SODALITE_CONFIG_PATH=${SODALITE_CONFIG_DIR}/${APPNAME}.rc
[ -f $SODALITE_CONFIG_PATH ] || SODALITE_CONFIG_PATH=/etc/${APPNAME}.rc
export SODALITE_CONFIG_PATH

# adjust the delay time in ms curses waits for an escape sequence to happen after pressing ESC
export ESCDELAY=0

python $(dirname $(readlink -f "$0"))/main.py
