name: Check
on: push
jobs:
  check:
    name: Lint, type-check and test the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Install virtualenv
        run: sudo pip install virtualenv

      - name: Setup venv
        run: make venv

      - name: Lint
        run: make lint

      - name: Type-Check
        run: make type-check

      - name: Run tests
        run: make test

      - name: Create type coverage badge
        # if: github.ref == 'refs/head/master'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: dfd1ab3f3a19522e0d2b0c94c409ba78
          filename: sodalite-type-coverage.json
          label: typing
          message: 1%
          color: orange
