name: check
on:
  pull_request:
    branches: [ master ]
jobs:
  check:
    name: run checks
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: restore dependencies from cache
        id: cache
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('setup.py') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make deps

      - name: lint code
        run: make lint

      - name: type-check
        id: type-check
        run: |
          make type-check
          export TYPE_COVERAGE=$(make type-coverage)
          echo "::set-output name=TYPE_COVERAGE::$TYPE_COVERAGE"

      - name: run tests
        run: make test

      # see https://github.com/marketplace/actions/dynamic-badges
      - name: create type coverage badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: dfd1ab3f3a19522e0d2b0c94c409ba78
          filename: sodalite-type-coverage.json
          label: typing
          message: ${{ steps.type-check.outputs.TYPE_COVERAGE }}%
          color: orange
