name: Check
on: push
jobs:
  check:
    name: Lint, type-check and test the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'

      - name: Print python version
        run: python --version

      - name: Install virtualenv
        run: sudo pip install virtualenv


      - name: Setup venv
        run: make venv

      - name: Lint
        run: make lint

      - name: Type-Check
        run: make type-check

      - name: Run tests
        run: make test
