name: downstream packaging

on:
  push:
    tags:
      - 'v*'

jobs:
  aur-publish:
    name: update aur package
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Validate & update checksums
        uses: datakrama/archlinux-package-action@v1
        with:
          path: packaging/aur
          updpkgsums: true

      - name: publish
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: sodalite
          pkgbuild: packaging/arch/PKGBUILD
          commit_username: "Heiko Nickerl"
          commit_email: "dev@hnicke.de"
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package

  debian-package:
    name: build debian package
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: prepare package
        run: ./packaging/deb/assemble

      - name: build debian package
        uses: dawidd6/action-debian-package@v1
        with:
          source_directory: packaging/deb/pkg
          artifacts_directory: packaging/deb/build

      - name: upload debian package to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: packaging/deb/build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}